---
- hosts: foo
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"

  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - role: trombik.hosts
    - role: trombik.hostname
    - role: trombik.sudo
    - role: trombik.tmux
    - role: trombik.vim
    - role: trombik.zsh
  vars:
